CREATE TABLE `SeeMst1` (
  `SeeOdrCod` char(10) CHARACTER SET utf8 NOT NULL,
  `SeeAdpDte` char(8) CHARACTER SET utf8 NOT NULL,
  `SeeSotCod` char(4) CHARACTER SET utf8 NOT NULL,
  `SeeTrnPrt` char(3) CHARACTER SET utf8 NOT NULL,
  `SeeSlpCod` char(5) CHARACTER SET utf8 DEFAULT '',
  `SeeCodTyp` char(1) CHARACTER SET utf8 DEFAULT '',
  `SeeKorNam` varchar(120) CHARACTER SET utf8 DEFAULT '',
  `SeeEngNam` varchar(120) CHARACTER SET utf8 DEFAULT '',
  `SeeShtNam` char(12) CHARACTER SET utf8 DEFAULT '',
  `SeeMdcTyp` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeElcCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeItmCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeAstCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeMthCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeAddCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeAddNon` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeePhrTyp` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeSlpTyp` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeDivYon` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeDrgCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeUsgCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeRepYon` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeUntQty` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeUntCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeMakCmp` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeComNam` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeAdmCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeTotQty` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeTotTms` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeOutLab` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeSpmPos` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeXryPtb` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeCalTyp` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeSpcAmt` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeCodDiv` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeRelCod` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeTrnDep` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeExpDte` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeCurStt` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeDisYon` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeUpdDtm` char(8) CHARACTER SET utf8 DEFAULT '',
  `SeeUidCod` char(8) CHARACTER SET utf8 DEFAULT '',
  
  
  PRIMARY KEY (`SeeOdrCod`,`SeeAdpDte`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;


